# Grafana picks up any ConfigMap in the monitoring namespace labeled `grafana_dashboard: "1"`
# via the sidecar that kube-prometheus-stack enables by default.

locals {
  # Operational ecommerce dashboards — auto-discovered from dashboards/ecommerce-*.json
  # Regenerate generated dashboards: python3 dashboards/generate.py
  ecommerce_dashboard_files = fileset("${path.module}/dashboards", "ecommerce-*.json")
  ecommerce_dashboards = {
    for f in local.ecommerce_dashboard_files :
    trimsuffix(f, ".json") => {
      file   = "${path.module}/dashboards/${f}"
      folder = "ecommerce"
    }
  }

  # SRE teaching dashboards — generated by ../../dashboards/generate.py
  sre_dashboard_files = fileset("${path.module}/../../dashboards", "[0-9]*-sre-*.json")
  sre_dashboards = {
    for f in local.sre_dashboard_files :
    trimsuffix(f, ".json") => {
      file   = "${path.module}/../../dashboards/${f}"
      folder = "sre-teaching"
    }
  }

  all_dashboards = merge(local.ecommerce_dashboards, local.sre_dashboards)
}

resource "kubernetes_config_map_v1" "dashboard" {
  for_each = local.all_dashboards

  metadata {
    name      = "ecommerce-${replace(each.key, ".", "-")}"
    namespace = var.monitoring_namespace
    labels = {
      grafana_dashboard           = "1"
      "app.kubernetes.io/part-of" = "ecommerce"
    }
    annotations = {
      "k8s-sidecar-target-directory" = "/tmp/dashboards/${each.value.folder}"
    }
  }

  data = {
    "${each.key}.json" = file(each.value.file)
  }
}
