apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "ecommerce.namespace" . }}
  labels:
    app: ecommerce
    environment: {{ .Values.global.environment }}
    {{- include "ecommerce.labels" . | nindent 4 }}
