apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-2-tier.fullname" . }}-config
  labels:
    {{- include "helm-2-tier.labels" . | nindent 4 }}
data:
  FLASK_APP: {{ .Values.config.FLASK_APP }}
