apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-2-tier.fullname" . }}-secret
  labels:
    {{- include "helm-2-tier.labels" . | nindent 4 }}
type: Opaque
data:
  db_link: {{ .Values.secret.db_link }}
