apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-2-tier.fullname" . }}
  labels:
    {{- include "helm-2-tier.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "helm-2-tier.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
