apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ include "ecommerce.namespace" . }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.database.user }}
  POSTGRES_PASSWORD: {{ .Values.database.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: {{ include "ecommerce.namespace" . }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.redis.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: {{ include "ecommerce.namespace" . }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.user }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ include "ecommerce.namespace" . }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret }}
  RAZORPAY_KEY_ID: {{ .Values.secrets.razorpay.keyId }}
  RAZORPAY_KEY_SECRET: {{ .Values.secrets.razorpay.keySecret }}
  RAZORPAY_WEBHOOK_SECRET: {{ .Values.secrets.razorpay.webhookSecret }}
